name: Node.js CI with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [21.6.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: |
        npm test -- --coverage

 token: e80b9f4e-4668-4adb-a997-044d6e9ac215

 - name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    slug: Emmyfrank/backend
